[package]
name = "patrician-crawler"
version = "0.9.0"
authors = ["janmo"]

[dependencies]
winapi = "0.2"
kernel32-sys = "0.2.2"
wio = "0.1.1"
time = "0.1.35"
serde = "*"
serde_json = "*"
env_logger = "*"
log = "*"
rand = "*"
serde_macros = "*"
clippy = "*"

[dependencies.ws]
version = "*"